ALTER TABLE "user" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS user_id_seq CASCADE;
ALTER TABLE "user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('user', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "user"), 1), false);

ALTER TABLE "import" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS import_id_seq CASCADE;
ALTER TABLE "import" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('import', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "import"), 1), false);

ALTER TABLE "location" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS location_id_seq CASCADE;
ALTER TABLE "location" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('location', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "location"), 1), false);

ALTER TABLE "export" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS export_id_seq CASCADE;
ALTER TABLE "export" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('export', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "export"), 1), false);

ALTER TABLE "integration" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS integration_id_seq CASCADE;
ALTER TABLE "integration" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('integration', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "integration"), 1), false);

ALTER TABLE "region" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS region_id_seq CASCADE;
ALTER TABLE "region" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('region', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "region"), 1), false);

ALTER TABLE "trip" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS trip_id_seq CASCADE;
ALTER TABLE "trip" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('trip', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "trip"), 1), false);

ALTER TABLE "place" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS place_id_seq CASCADE;
ALTER TABLE "place" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('place', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "place"), 1), false);

ALTER TABLE "owntracks_mqtt_message" ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS owntracks_mqtt_message_id_seq CASCADE;
ALTER TABLE "owntracks_mqtt_message" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT SETVAL(pg_get_serial_sequence('owntracks_mqtt_message', 'id'), COALESCE((SELECT MAX(id) + 1 FROM "owntracks_mqtt_message"), 1), false);
